services:
  auth-pgsql:
    image: postgres:17
    container_name: pgsql
    environment:
      POSTGRES_DB: "ID"
      POSTGRES_USER: "Admin"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - auth_pgsql_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  auth_pgsql_data: