services:
  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    depends_on:
      - postgres
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PWD=secret
      - DB_DATABASE=mydb
      - MIGRATE_DIR=/Users/konoko/Documents/golang/Mayberries/internal/repo/migrate
    networks:
      - backend

  background_worker_service:
    build:
      context: ./background_worker_service
      dockerfile: Dockerfile
    container_name: background_worker_service
    networks:
      - backend

  catalog_service:
    build:
      context: ./catalog_service
      dockerfile: Dockerfile
    container_name: catalog_service
    networks:
      - backend

  infrastructure:
    build:
      context: ./infrastructure
      dockerfile: Dockerfile
    container_name: infrastructure
    networks:
      - backend

  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    container_name: order_service
    ports:
      - "8080:8080"
    networks:
      - backend

  reviews_service:
    build:
      context: ./reviews_service
      dockerfile: Dockerfile
    container_name: reviews_service
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: