services:
  auth_service:
    build: auth_service
    container_name: auth_service


  background_worker-service:
    build: ../background_worker
    container_name: background_worker


  catalog_service:
    build: catalog_service
    container_name: catalog_service


  order_service:
    build: order_service
    container_name: order_service
    ports:
      - "8080:8080"

  reviews_service:
    build: ./Reviews_Service
    container_name: reviews_service