services:
  auth_service:
    build: auth_service
    container_name: auth_service
    depends_on:
      - postgres
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PWD=secret
      - DB_DATABASE=mydb
      - MIGRATE_DIR=/app/migrations

    networks:
      - backend

  background_worker-service:
    build: background_worker_service
    container_name: background_worker_service
    networks:
      - backend

  catalog_service:
    build: catalog_service
    container_name: catalog_service
    networks:
      - backend

  infrastructure:
    build: infrastructure
    container_name: infrastructure
    networks:
      - backend

  order_service:
    build: order_service
    container_name: order_service
    ports:
      - "8003:8003"
    networks:
      - backend

  reviews_service:
    build: reviews_service
    container_name: reviews_service
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: